#+TITLE: Statistical Software Workshops From The RTC Team IQSS
#+AUTHOR: Ista Zahn
#+EMAIL: istazahn@gmail.com


Most of the notes for these workshops were written in
http://orgmode.org markup and should be viewed in the
http://www.gnu.org/software/emacs/ text editor >= version 24.3 with
orgmode >= 8.0. If you use a version of emacs >= 24.3 the required
emacs packages can be installed by opening the StartHere.el file in
the "Classes" folder. While I have made an effort to make these
materials usable by someone new to emacs and org-mode, working with
these materials will be much more pleasant if you have at least some
experience with emacs and the org-mode emacs package.

These files includes literate code blocks that can be executed in
emacs by typing the command 'M-x org-babel-execute-src-block', which is
usually bound to 'C-c C-c' (See http://oreilly.com/openbook/mh/conv.htm
if you are unfamiliar with emacs key conventions). You can execute all 
the example code in  this document using the command 
'M-x org-babel-execute-buffer'.  You must have R installed on your system,
and you must have the emacs package 'ess' installed (ess can be auto-installed
by opening the "StartHere.el" file in the "Classes" folder).

The contents of these documents can be exported to a variety of formats,
including pdf slides (requires a LaTeX distribution, preferably
TeXlive or MacTex), html, or text. To access the export menu run the
command 'M-x org-export-dispatch', usually bound to 'C-c C-e' 
(choose "Beamer" for pdf slide export). Export to pdf requires python 
and the python module 'Pygments' (you must install this manually).


For pdf/beamer I like to set 'exports results'. For html set either
'exports results' or 'exports both'. For script/text export set
'exports code'. In this later case my system is not fully automated;
export to text, open the .txt file and save it with a .R
extension. Coment out everything (C-x h M-x comment-region) and then
use find and replace to uncomment to the code sections (M-x replace-string).
Available export tags include 'prototype' (exercise solutions) 'labsetup'
(instructions specific to IQSS lab machine setup), 'setup' (generic setup 
instructions) and 'mitsetup' (instructions specific to MIT Athena 
computing cluster setup).
