#!/usr/bin/Rscript

fname <- as.character(commandArgs(trailingOnly = TRUE))

oname <- gsub("\\.Rmd$", ".md", fname)

ftext <- gsub("purl *= * FALSE",
              "purl=FALSE, results='hide', echo = FALSE",
              readLines(fname))

library(knitr)

opts_chunk$set(eval = FALSE)

ftext = paste(ftext, collapse = '\n')

knit(text = ftext, output = oname)
