(TeX-add-style-hook "StataIntro"
 (lambda ()
    (LaTeX-add-labels
     "sec-1"
     "sec-2"
     "sec-3"
     "sec-4"
     "sec-5")
    (TeX-run-style-hooks
     "fancyvrb"
     "minted"
     "tikz"
     "hyperref"
     "amssymb"
     "wasysym"
     "marvosym"
     "textcomp"
     "amsmath"
     "ulem"
     "normalem"
     "rotating"
     "wrapfig"
     "float"
     "longtable"
     "graphicx"
     "fixltx2e"
     ""
     "fontenc"
     "T1"
     "inputenc"
     "utf8"
     "latex2e"
     "beamer10"
     "beamer"
     "smaller"
     "table")))

