---
title: "Exercises"
output: ioslides_presentation
---

Exercise 0 {.smaller}
----------

1.  Download and extract the data from 
    http://tutorials.iq.harvard.edu/R/RDataWrangling/data/boysNames.zip

You can download the file using a web browser, and extract using your file browser.
For bonus points you can try doing it using R, but this is not required.

2.  Locate the file named `1996boys_tcm77-254026.xlsx` and open it in
    a spreadsheet. (If you don't have a spreadsheet program installed on
    your computer you can downloads one from
    https://www.libreoffice.org/download/download/). What issues can you
    identify that might make working with these data more difficult?

3.  Locate the file named `2015boysnamesfinal.xlsx` and open it in a
    spreadsheet. In what ways is the format different than the format
    of `1996boys_tcm77-254026.xlsx`? How might these differences make
    it more difficult to work with these data?


Exercise 1
-----------

  1. Write a function that takes a file name as an argument and reads
     the worksheet containing "Table 1" from that file. Don't forget
     to skip the first 6 rows.
     
  2. Test your function by using it to read *one* of the boys names
     Excel files.
     
  3. Use the `map` function to read data from all the Excel files,
     using the function you wrote in step 1.

Exercise 2
-----------

  1. Write a function that takes a `data.frame` as an argument and
     returns a modified version including only columns named `Name`,
     `Name__1`, `Count`, or `Count__1`. 
     
  2. Test your function on the first `data.frame` in the list of baby
     names data.
     
  3. Use the `map` function to each `data.frame` in the list of baby
     names data.


Exercise 3: Cleanup all the data
------------------------------

In the previous examples we learned how to drop empty rows with
`filter`, select only relevant columns with `select`, and re-arrange
our data with `select` and `bind_rows`. In each case we applied the
changes only to the first element of our `boysNames` list.

Your task now is to use the `map` function to apply each of these
transformations to all the elements in `boysNames`.



Exercise 4
-------------------------

Turn the list of boys names data.frames into a single table. 

Create a directory under `data/all` and write the data to a `.csv`
file.

Finally, repeat the previous exercise, this time working with the data
in one big table.
